return {
  "navarasu/onedark.nvim",
  name = "onedark",
  priority = 1000,
  lazy = false,
  config = function()
    require("onedark").setup({
      -- `onedark.nvim` fornece o motor de destaque. Esta e a paleta One Dark
      -- definida pelo usuario; o fundo e opaco para #282c34 aparecer de fato.
      style = "dark",
      transparent = false,
      term_colors = true,
      colors = {
        black = "#282C34",
        bg0 = "#282C34",
        bg1 = "#21252B",
        bg2 = "#2C313A",
        bg3 = "#3E4451",
        bg_d = "#21252B",
        bg_blue = "#3E4451",
        fg = "#ABB2BF",
        grey = "#5C6370",
        light_grey = "#ABB2BF",
        red = "#E06C75",
        green = "#98C379",
        yellow = "#E5C07B",
        orange = "#D19A66",
        blue = "#61AFEF",
        purple = "#C678DD",
        cyan = "#56B6C2",
      },
      highlights = {
        NormalFloat = { fg = "$fg", bg = "$bg1" },
        FloatBorder = { fg = "$blue", bg = "$bg1" },
        Pmenu = { fg = "$fg", bg = "$bg1" },
        PmenuSel = { fg = "$fg", bg = "$bg3", fmt = "bold" },
        Visual = { bg = "$bg_blue" },
        CursorLine = { bg = "$bg_d" },
        LineNr = { fg = "$grey" },
        CursorLineNr = { fg = "$light_grey", bg = "$bg_d", fmt = "bold" },
        MiniIndentscopeSymbol = { fg = "$bg3" },
        WinSeparator = { fg = "$bg1" },
        RenderMarkdownH1 = { fg = "$fg", fmt = "bold" },
        RenderMarkdownH2 = { fg = "$blue", fmt = "bold" },
        RenderMarkdownH3 = { fg = "$purple", fmt = "bold" },
        RenderMarkdownH4 = { fg = "$green", fmt = "bold" },
        RenderMarkdownH5 = { fg = "$yellow", fmt = "bold" },
        RenderMarkdownH6 = { fg = "$grey", fmt = "bold" },
        RenderMarkdownH1Bg = { bg = "$bg0" },
        RenderMarkdownH2Bg = { bg = "$bg0" },
        RenderMarkdownH3Bg = { bg = "$bg0" },
        RenderMarkdownH4Bg = { bg = "$bg0" },
        RenderMarkdownH5Bg = { bg = "$bg0" },
        RenderMarkdownH6Bg = { bg = "$bg0" },
        RenderMarkdownBullet = { fg = "$fg" },
        RenderMarkdownDash = { fg = "$grey" },
        RenderMarkdownCode = { bg = "$bg1" },
        RenderMarkdownCodeInline = { bg = "$bg1" },

        ["@attribute"] = { fg = "$yellow" },
        ["@constant"] = { fg = "$purple" },
        ["@constructor"] = { fg = "$blue", fmt = "italic" },
        ["@function"] = { fg = "$blue" },
        ["@function.call"] = { fg = "$blue" },
        ["@function.method"] = { fg = "$blue" },
        ["@keyword"] = { fg = "$purple" },
        ["@keyword.import"] = { fg = "$purple" },
        ["@keyword.modifier"] = { fg = "$purple" },
        ["@number"] = { fg = "$cyan" },
        ["@operator"] = { fg = "$fg" },
        ["@property"] = { fg = "$red" },
        ["@punctuation.bracket"] = { fg = "$fg" },
        ["@punctuation.delimiter"] = { fg = "$orange" },
        ["@string"] = { fg = "$green" },
        ["@type"] = { fg = "$yellow" },
        ["@type.builtin"] = { fg = "$orange" },
        ["@variable"] = { fg = "$red" },
        ["@variable.builtin"] = { fg = "$red" },
        ["@variable.member"] = { fg = "$red" },
        ["@variable.parameter"] = { fg = "$red" },

        ["@lsp.type.annotation.java"] = { fg = "$yellow" },
        ["@lsp.type.class.java"] = { fg = "$yellow" },
        ["@lsp.type.enum.java"] = { fg = "$yellow" },
        ["@lsp.type.interface.java"] = { fg = "$purple" },
        ["@lsp.type.keyword.java"] = { fg = "$purple" },
        ["@lsp.type.method.java"] = { fg = "$blue" },
        ["@lsp.type.namespace.java"] = { fg = "$fg" },
        ["@lsp.type.property.java"] = { fg = "$red" },
        ["@lsp.type.variable.java"] = { fg = "$red" },
      },
      code_style = {
        comments = "italic",
        keywords = "none",
        functions = "none",
        strings = "none",
        variables = "none",
      },
    })
    require("onedark").load()
    vim.g.colors_name = "one-dark-custom"
  end,
}
